datagrids:
    invoice-files-grid:
        source:
            acl_resource: invoice.file_view
            type: orm
            query:
                select:
                    - invoiceFile.id
                    - file.originalFilename as fileName
                    - relatedAccount.name as relatedAccountName
                    - category.name as categoryName
                    - parentCategory.name as parentCategoryName
                    - invoiceFile.uploadedAt as uploadedAt
                from:
                    - { table: 'Custom\Bundle\InvoiceBundle\Entity\InvoiceFile', alias: invoiceFile }
                join:
                    left:
                        - { join: invoiceFile.relatedAccount, alias: relatedAccount }
                        - { join: invoiceFile.file, alias: file }
                        - { join: invoiceFile.category, alias: category }
                        - { join: category.category, alias: parentCategory }
        columns:
            fileName:
                label: oro.invoice.file_name.label
            parentCategoryName:
                label: oro.invoice.subcategory.category.label
            categoryName:
                label: oro.invoice.subcategory.label
            relatedAccountName:
                label: oro.invoice.related_account.label
            uploadedAt:
                inline_editing:
                    enable: false
                label: oro.invoice.uploaded_at.label
                frontend_type: datetime
        sorters:
            columns:
                relatedAccountName:
                    data_name: relatedAccountName
                categoryName:
                    data_name: categoryName
                parentCategoryName:
                    data_name: parentCategoryName
                uploadedAt:
                    data_name: invoiceFile.uploadedAt
            default:
                uploadedAt: DESC
        filters:
            columns:
                fileName:
                    type: string
                    data_name: fileName
                categoryName:
                    type: string
                    data_name: categoryName
                parentCategoryName:
                    type: string
                    data_name: parentCategoryName
                relatedAccountName:
                    type: string
                    data_name: relatedAccountName
                uploadedAt:
                    type: datetime
                    data_name: invoiceFile.uploadedAt
        properties:
            id: ~
            view_link:
                type:         url
                route:        invoice_file_view
                params:       [ id ]
            update_link:
                type:         url
                route:        invoice_file_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        oro_invoice_files_api_delete_file
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: invoice.file_view
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: invoice.file_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: invoice.file_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link

    invoice-subcategories-grid:
        source:
            acl_resource: invoice.subcategories_view
            type: orm
            query:
                select:
                    - invoiceSubCategory.id
                    - invoiceSubCategory.name as invoiceSubCategoryName
                    - invoiceCategory.name as invoiceCategoryName
                from:
                    - { table: 'Custom\Bundle\InvoiceBundle\Entity\InvoiceSubCategory', alias: invoiceSubCategory }
                join:
                    left:
                        - { join: invoiceSubCategory.category, alias: invoiceCategory }
        columns:
            invoiceSubCategoryName:
                label: oro.invoice.subcategory.name.label
            invoiceCategoryName:
                label: oro.invoice.subcategory.category.label
        sorters:
            columns:
                invoiceSubCategoryName:
                    data_name: invoiceSubCategoryName
                invoiceCategoryName:
                    data_name: invoiceCategoryName
        filters:
            columns:
                invoiceSubCategoryName:
                    type: string
                    data_name: invoiceSubCategoryName
                invoiceCategoryName:
                    type: string
                    data_name: invoiceCategoryName
        properties:
            id: ~
            view_link:
                type:         url
                route:        invoice_subcategory_view
                params:       [ id ]
            update_link:
                type:         url
                route:        invoice_subcategory_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        oro_invoice_subcategories_api_delete_subcategory
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: invoice.subcategory_view
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: invoice.subcategory_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: invoice.subcategory_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link

    invoice-categories-grid:
        source:
            acl_resource: invoice.categories_view
            type: orm
            query:
                select:
                    - invoiceCategory.id
                    - invoiceCategory.name as invoiceCategoryName
                    - invoiceCategory.invoiceFormEnabled as invoiceFormEnabled
                from:
                    - { table: 'Custom\Bundle\InvoiceBundle\Entity\InvoiceCategory', alias: invoiceCategory }
        columns:
            invoiceCategoryName:
                label: oro.invoice.category.name.label
            invoiceFormEnabled:
                label: oro.invoice.category.invoice_form_enabled.label
        sorters:
            columns:
                invoiceCategoryName:
                    data_name: invoiceCategoryName
                invoiceFormEnabled:
                    data_name: invoiceFormEnabled
        filters:
            columns:
                invoiceCategoryName:
                    type: string
                    data_name: invoiceCategoryName
                invoiceFormEnabled:
                    type: choice
                    data_name: invoiceFormEnabled
                    options:
                        field_options:
                            multiple: true
                            choices:
                                'True': 1
                                'False': 0
                    translatable_options: true
        properties:
            id: ~
            view_link:
                type:         url
                route:        invoice_category_view
                params:       [ id ]
            update_link:
                type:         url
                route:        invoice_category_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        oro_invoice_categories_api_delete_category
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: invoice.category_view
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: invoice.category_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: invoice.category_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
