navigation:
    menu_config:
        items:
            invoice_tab:
                label: 'oro.invoice.tab'
                uri: '#'
                extras:
                    position: 30
                    icon: fa-book
            invoice_files:
                label: 'oro.invoice.files'
                route: invoice_file_index
            invoice_categories:
                label: 'oro.invoice.categories'
                route: invoice_category_index
            invoice_subcategories:
                label: 'oro.invoice.subcategories'
                route: invoice_subcategory_index

        tree:
            application_menu:
                children:
                    invoice_tab:
                        children:
                            invoice_files: ~
                            invoice_categories: ~
                            invoice_subcategories: ~
